# Generated by Django 4.2.6 on 2023-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
