# Generated by Django 4.2.6 on 2023-11-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_eleve_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='matieres',
        ),
    ]
