# Generated by Django 4.2.6 on 2023-11-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_eleve_user_alter_enseignant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
    ]
