# Generated by Django 4.2.6 on 2023-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_eleve_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.IntegerField(null=True),
        ),
    ]
