# Generated by Django 4.2.6 on 2023-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.FloatField(null=True),
        ),
    ]
